### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ghost** [patrickmichalina/fusebox-angular-universal-starter#528]
I'm getting this error when trying to login:

```
Unhandled Promise rejection: JSON.parse: unexpected character at line 1 column 1 of the JSON data ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack trace:
_parseJson@http://localhost:8000/js/vendors.js:237145:20
_getSourceMapConsumer/</sourceMapConsumerPromise</<@http://localhost:8000/js/vendors.js:237328:51
Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:8000/js/vendors.js:2122:17
Zone$1</Zone</Zone.prototype.run@http://localhost:8000/js/vendors.js:1872:24
scheduleResolveOrReject/<@http://localhost:8000/js/vendors.js:2592:52
Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:8000/js/vendors.js:2155:17
Zone$1</Zone</Zone.prototype.runTask@http://localhost:8000/js/vendors.js:1922:28
drainMicroTaskQueue@http://localhost:8000/js/vendors.js:2329:25
Zone$1</ZoneTask</ZoneTask.invokeTask@http://localhost:8000/js/vendors.js:2234:21
ZoneTask/this.invoke@http://localhost:8000/js/vendors.js:2219:28
scheduleTask/target[XHR_LISTENER]@http://localhost:8000/js/vendors.js:4660:25
 _parseJson@http://localhost:8000/js/vendors.js:237145:20
_getSourceMapConsumer/</sourceMapConsumerPromise</<@http://localhost:8000/js/vendors.js:237328:51
Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:8000/js/vendors.js:2122:17
Zone$1</Zone</Zone.prototype.run@http://localhost:8000/js/vendors.js:1872:24
scheduleResolveOrReject/<@http://localhost:8000/js/vendors.js:2592:52
Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:8000/js/vendors.js:2155:17
Zone$1</Zone</Zone.prototype.runTask@http://localhost:8000/js/vendors.js:1922:28
drainMicroTaskQueue@http://localhost:8000/js/vendors.js:2329:25
Zone$1</ZoneTask</ZoneTask.invokeTask@http://localhost:8000/js/vendors.js:2234:21
ZoneTask/this.invoke@http://localhost:8000/js/vendors.js:2219:28
scheduleTask/target[XHR_LISTENER]@http://localhost:8000/js/vendors.js:4660:25
 vendors.js:2406:17
```
 
Happens at the "new firebase.auth.GoogleAuthProvider()" line in the auth.service.ts
Any provider that I try to use gives me this error. Any idea what I am missing?
(The providers are active in the firebase console)

**Comment by patrickmichalina** [comment]
Oh sorry, for error logging there is an issue at the moment!

Please comment out the GlobalErrorHandler in app.module. It is formatting the Firebase errors incorrectly.

**Comment by ghost** [comment]
firebase.auth is undefined

and if I use the login/password 'provider', I get the promise back, but the login never happens, loading animation keeps running and no real auth is performed.
Thanks for the info on the Error Handler anyway.

**Comment by patrickmichalina** [comment]
firebase.auth ? hmmmmmm

This section of code isn't super fleshed out. Probably tons of bugs. Thanks for reporting.

**Comment by billbarni** [comment]
I don't understand why in the live demo it works and when run locally it does not.

**Comment by patrickmichalina** [comment]
Have you guys updated the server settings here to match your firebase config?

https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/server/service-account.json

**Comment by billbarni** [comment]
Yes, as you already pointed in issue #479

**Comment by billbarni** [comment]
1. cloned this repo
2. npm install
3. created a firebase project in firebase console
4. 'activated' storage
5. copy and pasted configs in: seed.settings.json, settings.ts, base.ts
6. generate cryptos for service account and pasted configs in: service-account.json
7. copy remaining service account configs into '.env' file in root folder
8. activate auth providers in firebase console, create a user and copy the user uuid to seed.supersusers.json
9. npm run gen.config, npm run firebase.update, npm run firebase.seed.superusers
10. comment out the GlobalErrorHandler from app.module.ts
11. npm run start

'firebase.auth is undefined' on login attemp using any provider except login/pass combo.

'res.settings.assets is undefined' on login attemp using login/password 'provider' because avatar does not exist, its not important though... but then again the login loading animation stays onscreen and the auth never happens even though I got the promisse back.
removing the avatar photoUrl line allows the auth to go further, but strage things happen, like a error when trying to update user "name" in account settings, saying "missing user".
logging out does not work also.

the code is very nice looking and professional, unfortunately I'm not experienced enough to fix it. I'm giving up on this seed. Thanks A LOT for the infos Mr. Patrick, but opening this issues on an open source project is going to take too much of your time and attention to help me out.

**Comment by patrickmichalina** [comment]
@billbarni Thanks so much for this feedback! I definitely want to get this fixed, it should be clearer how to get a new project off the ground with ease. I am a bit busy at the moment but hopefully this weekend I can put in some maintenance to get these Auth issues resolved :)

Also, the firebase auth system is a little bit more challenging to integrate into Universal than I anticipated. 

I will replicate the steps you did to see why firebase.auth is undefined. Thanks again!

**Comment by patrickmichalina** [comment]
To all following this thread, I am starting a cleaner repo without all the ONLY the important build steps and none of the built in things like Material/Firebase/etc. I will get to this auth issue when I can, but moving forward I will be reducing my use of firebase, its auth is just not very fast :/

Check out the new repo if you are interested in this empty starter https://github.com/patrickmichalina/fusing-angular

it has AOT support now!

**Comment by billbarni** [comment]
Have you seen this project?
https://github.com/hamedbaatour/angularfire-lite
